////
////  Page1ListViewControllerTests.swift
////  BuyerClean
////
////  Created by Peanuz on 4/9/2562 BE.
////  Copyright (c) 2562 SCB. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import BuyerClean
//import XCTest
//
//class Page1ListViewControllerTests: XCTestCase
//{
//  // MARK: Subject under test
//
//  var sut: Page1ListViewController!
//  var window: UIWindow!
//
//  // MARK: Test lifecycle
//
//  override func setUp()
//  {
//    super.setUp()
//    window = UIWindow()
//    setupPage1ListViewController()
//  }
//
//  override func tearDown()
//  {
//    window = nil
//    super.tearDown()
//  }
//
//  // MARK: Test setup
//
//  func setupPage1ListViewController()
//  {
//    let bundle = Bundle.main
//    let storyboard = UIStoryboard(name: "Main", bundle: bundle)
//    sut = storyboard.instantiateViewController(withIdentifier: "Page1ListViewController") as! Page1ListViewController
//  }
//
//  func loadView()
//  {
//    window.addSubview(sut.view)
//    RunLoop.current.run(until: Date())
//  }
//
//  // MARK: Test doubles
//
//  class Page1ListBusinessLogicSpy: Page1ListBusinessLogic
//  {
//    var doSomethingCalled = false
//
//    func doSomething(request: Page1List.Something.Request)
//    {
//      doSomethingCalled = true
//    }
//  }
//
//  // MARK: Tests
//
//  func testShouldDoSomethingWhenViewIsLoaded()
//  {
//    // Given
//    let spy = Page1ListBusinessLogicSpy()
//    sut.interactor = spy
//
//    // When
//    loadView()
//
//    // Then
//    XCTAssertTrue(spy.doSomethingCalled, "viewDidLoad() should ask the interactor to do something")
//  }
//
//  func testDisplaySomething()
//  {
//    // Given
//    let viewModel = Page1List.Something.ViewModel()
//
//    // When
//    loadView()
//    sut.displaySomething(viewModel: viewModel)
//
//    // Then
//    //XCTAssertEqual(sut.nameTextField.text, "", "displaySomething(viewModel:) should update the name text field")
//  }
//}
