//
//  Page1ListPresenterTests.swift
//  BuyerClean
//
//  Created by Peanuz on 4/9/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BuyerClean
import XCTest

class Page1ListPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: Page1ListPresenter!
  var viewControllerspy: Page1ListViewControllerInterfaceSpy!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPage1ListPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPage1ListPresenter()
  {
    sut = Page1ListPresenter()
    viewControllerspy = Page1ListViewControllerInterfaceSpy()
    sut.viewController = viewControllerspy
  }
  
  // MARK: Test doubles
  
  class Page1ListViewControllerInterfaceSpy: Page1ListViewControllerInterface {
    var displayPage1Called = false
    var sortPhonesCalled = false
    var passSelectedCalled = false
    var listViewModel: Page1Model.GetAPI.ViewModel?
    var sortViewModel: Page1Model.Sort.ViewModel?
    
    func displayPage1(viewModel: Page1Model.GetAPI.ViewModel) {
      listViewModel = viewModel
      displayPage1Called = true
    }
    
    func sortPhonePage1(viewModel: Page1Model.Sort.ViewModel) {
      sortViewModel = viewModel
      sortPhonesCalled = true
    }
    
    func passSelected() {
      passSelectedCalled = true
    }
    
    
  }
  
  // MARK: Tests
  
  func testPresentPage1() {
    // Given
    let response = Page1Model.GetAPI.Response(success: true, json: [Phone(rating: 4.6, id: 1, thumbImageURL: "testURL", price: 179.99, brand: "Moto", name: "Moto E4 Plus", description: "First place")])
    
    // When
    sut.presentPage1(response: response)
    
    // Then
    if let viewModel = viewControllerspy.listViewModel {
      let data = DisplayedPhone(id: 1, rating: 4.6, thumbImageURL: "testURL", price: 179.99, name: "Moto E4 Plus", description: "First place")
      XCTAssertTrue(viewModel.success)
      XCTAssertEqual(viewModel.json, [data])
    } else {
      XCTFail()
    }
  }
  
  func testSortPage1() {
    //Given
    let response = Page1Model.Sort.Response(sortPhone: [Phone(rating: 4.6, id: 1, thumbImageURL: "testURL", price: 179.99, brand: "Moto", name: "Moto E4 Plus", description: "First place")])

    //When
    sut.sortPage1(response: response)

    //Then
    if let viewModel = viewControllerspy.sortViewModel {
      let data = DisplayedPhone(id: 1, rating: 4.6, thumbImageURL: "testURL", price: 179.99, name: "Moto E4 Plus", description: "First place")
      XCTAssertEqual(viewModel.array, [data])
    } else {
      XCTFail()
    }
  }
  
}
