//
//  Page1ListWorkerTests.swift
//  BuyerClean
//
//  Created by Peanuz on 4/9/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BuyerClean
import XCTest

class Page1ListWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: Page1WokerAPI!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPage1ListWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPage1ListWorker()
  {
    sut = Page1WokerAPI()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
