//
//  Page2DetailsInteractorTests.swift
//  BuyerClean
//
//  Created by Peanuz on 5/9/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BuyerClean
import XCTest

class Page2DetailsInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: Page2DetailsInteractor!
  var presenterSpy: Page2DetailsPresenterSpy!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPage2DetailsInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPage2DetailsInteractor(){
    sut = Page2DetailsInteractor()
    presenterSpy = Page2DetailsPresenterSpy()
    sut.presenter = presenterSpy
  }
  
  // MARK: Test doubles
  class WokerSpy: Page2WokerAPI {
    var workerCalled = false
    override func getImageAPI(id: Int, completion: @escaping (Result<[ImagePhone], Error>) -> Void) {
      workerCalled = true
      completion(.success([ImagePhone(url: "URL", id: 1, mobileID: 1)]))
    }
  }
  
  class Page2DetailsPresenterSpy: Page2DetailsPresenterInterface {
    var presentDeatailsCalled = false
    var presentImageCalled = false
    var displayPhone : Page2Model.showDetails.Response?
    var displayImage : Page2Model.GetAPIImage.Response?
    func presentDeatails(response: Page2Model.showDetails.Response) {
      presentDeatailsCalled = true
      displayPhone = response
    }
    
    func presentImage(response: Page2Model.GetAPIImage.Response) {
      presentImageCalled = true
      displayImage = response
    }
    
  }
  
  // MARK: Tests
  func testShowDetails() {
    //Given
    sut.phone = Phone(rating: 4.6, id: 1, thumbImageURL: "testURL", price: 179.99, brand: "Moto", name: "Moto E4 Plus", description: "First place")
    //When
    let request = Page2Model.showDetails.Request()
    sut.showDetails(request: request)
    
    //Then
    if let viewModel = presenterSpy.displayPhone {
      let data = Phone(rating: 4.6, id: 1, thumbImageURL: "testURL", price: 179.99, brand: "Moto", name: "Moto E4 Plus", description: "First place")
      XCTAssertEqual(viewModel.json, data)
    } else {
      XCTFail()
    }
  }
  
  func testFeedAPIImage() {
    //Given
    sut.worker = WokerSpy()
    
    //When
    sut.feedAPIImage(request: Page2Model.GetAPIImage.Request(id: 1))
    
    //Then
    if let viewModel = presenterSpy.displayImage {
      let image = ImagePhone(url: "URL", id: 1, mobileID: 1)
      XCTAssertTrue(viewModel.success)
      XCTAssertEqual(viewModel.json, [image])
    } else {
      XCTFail()
    }
  }

}
