////
////  Page2DetailsWorkerTests.swift
////  BuyerClean
////
////  Created by Peanuz on 5/9/2562 BE.
////  Copyright (c) 2562 SCB. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//@testable import BuyerClean
//import XCTest
//
//class Page2DetailsWorkerTests: XCTestCase
//{
//  // MARK: Subject under test
//
//  var sut: Page2DetailsWorker!
//
//  // MARK: Test lifecycle
//
//  override func setUp()
//  {
//    super.setUp()
//    setupPage2DetailsWorker()
//  }
//
//  override func tearDown()
//  {
//    super.tearDown()
//  }
//
//  // MARK: Test setup
//
//  func setupPage2DetailsWorker()
//  {
//    sut = Page2DetailsWorker()
//  }
//
//  // MARK: Test doubles
//
//  // MARK: Tests
//
//  func testSomething()
//  {
//    // Given
//
//    // When
//
//    // Then
//  }
//}
