//
//  Page2DetailsPresenterTests.swift
//  BuyerClean
//
//  Created by Peanuz on 5/9/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import BuyerClean
import XCTest

class Page2DetailsPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: Page2DetailsPresenter!
  var viewControllerspy: Page2DetailsViewControllerInterfaceSpy!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPage2DetailsPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPage2DetailsPresenter()
  {
    sut = Page2DetailsPresenter()
    viewControllerspy = Page2DetailsViewControllerInterfaceSpy()
    sut.viewController = viewControllerspy
  }
  
  // MARK: Test doubles
  
  class Page2DetailsViewControllerInterfaceSpy: Page2DetailsViewControllerInterface {
    var displayPhoneCalled = false
    var displayImageCalled = false
    var detailsViewModel: Page2Model.showDetails.ViewModel?
    var imageViewModel: Page2Model.GetAPIImage.ViewModel?
    
    func displayPhone(viewModel: Page2Model.showDetails.ViewModel) {
      displayPhoneCalled = true
      detailsViewModel = viewModel
    }
    
    func displayImage(viewModel: Page2Model.GetAPIImage.ViewModel) {
      displayImageCalled = true
      imageViewModel = viewModel
    }
    
  }
  
  // MARK: Tests
  
  func testPresentDeatails(){
    // Given
   let response = Page2Model.showDetails.Response(json: Phone(rating: 4.6, id: 1, thumbImageURL: "testURL", price: 179.99, brand: "Moto", name: "Moto E4 Plus", description: "First place"))
    
    // When
    sut.presentDeatails(response: response)
    
    // Then
    if let viewModel = viewControllerspy.detailsViewModel {
      let data = Phone(rating: 4.6, id: 1, thumbImageURL: "testURL", price: 179.99, brand: "Moto", name: "Moto E4 Plus", description: "First place")
      XCTAssertEqual(viewModel.json, data)
    } else {
      XCTFail()
    }
  }
  
  func testPresentImage() {
    //Given
    let response = Page2Model.GetAPIImage.Response(success: true, json: [ImagePhone(url: "url", id: 1, mobileID: 1)])
    
    //When
    sut.presentImage(response: response)
    
    //Then
    if let viewModel = viewControllerspy.imageViewModel {
      let data = ImagePhone(url: "url", id: 1, mobileID: 1)
      XCTAssertTrue(viewModel.success)
      XCTAssertEqual(viewModel.json, [data])
    } else {
      XCTFail()
    }
  }
}
