//
//  Page1ListPresenter.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Page1ListPresenterInterface
{
    func presentPage1(response: Page1Model.GetAPI.Response)
    func sortPage1(response: Page1Model.Sort.Response)
}

class Page1ListPresenter: Page1ListPresenterInterface
{
  weak var viewController: Page1ListViewControllerInterface!
  
  // MARK: Do something
    
    func sortPage1(response: Page1Model.Sort.Response){
        let sortPhone: [DisplayedPhone] = response.sortPhone.map() { sortPhone in
            DisplayedPhone(id: sortPhone.id, rating: sortPhone.rating, thumbImageURL: sortPhone.thumbImageURL, price: sortPhone.price, name: sortPhone.name, description: sortPhone.description)
        }
        let viewModel = Page1Model.Sort.ViewModel(array: sortPhone)
        viewController?.sortPhonePage1(viewModel: viewModel)
    }
    
    func presentPage1(response: Page1Model.GetAPI.Response){
    let displayeds: [DisplayedPhone] = response.json.map() { phone in
        DisplayedPhone(id: phone.id, rating: phone.rating, thumbImageURL: phone.thumbImageURL, price: phone.price, name: phone.name, description: phone.description)
    }
    let viewModel = Page1Model.GetAPI.ViewModel(success: response.success, json: displayeds)
    viewController?.displayPage1(viewModel: viewModel)
  }
}
