//
//  Page1ListWorker.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON

protocol APIManagerProtocol {
    func getAPI(completion: @escaping (Swift.Result<[Phone], Error>) -> Void)
}

class APIManager : APIManagerProtocol{
    static let shared: APIManager = APIManager()

  func getAPI(completion: @escaping (Swift.Result<[Phone], Error>) -> Void)
  {
    let baseURL: String = "https://scb-test-mobile.herokuapp.com/api/mobiles/"
    AF.request(baseURL)
        .validate()
        .responseJSON { response in
            switch response.result {
            case .success:
                do {
                    let phone = try JSONDecoder().decode([Phone].self, from: response.data!)
                    completion(.success(phone))
                } catch (let error) {
                    completion(.failure(error))
                }
            case .failure(let error):
                completion(.failure(error))
            }
            
    }
  }
}
