//
//  Page1ListRouter.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Page1RouterDetails
{
  func navigateToPage2()
}

class Page1ListRouter: Page1RouterDetails{
    
  weak var viewController: Page1ListViewController!
    
    func navigateToPage2() {
        viewController.performSegue(withIdentifier: "showDetails", sender: nil)
    }
    
    func passDataToPage2Details(displayPhone: [DisplayedPhone] ,segue: UIStoryboardSegue){
        if segue.identifier == "showDetails" {
            let destinationVC = segue.destination as? Page2DetailsViewController
            let indexPath = viewController?.tableView.indexPathForSelectedRow
            if let indexPath = indexPath {
                let phone : DisplayedPhone = displayPhone[(indexPath as NSIndexPath).row]
                let item: DisplayedPhone = displayPhone[indexPath.item]
                destinationVC?.interactor.phone = item
                print("item: \(item)")
                print(phone)
                destinationVC?.interactor.mobileID = item.id
//                destinationVC?.interactor.description = item.description
//                destinationVC?.interactor.price = item.price
//                destinationVC?.interactor.rating = item.rating
            }
        }
    }
}
