//
//  Page2DetailsInteractor.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Page2DetailsInteractorInterface
{
    func feedAPI(request:Page2Model.GetAPIImage.Request)
    func showDetails(request: Page2Model.showDetails.Request)
    var phone: Phone? {get set}

}

class Page2DetailsInteractor: Page2DetailsInteractorInterface
{
    var phone: Phone?
    var imagePhone: [ImagePhone] = []
    var presenter: Page2DetailsPresenterInterface?
    var worker: APIManagerImage?
  
  // MARK: Do something
  
  func showDetails(request: Page2Model.showDetails.Request){
    let response = Page2Model.showDetails.Response(json: phone!)
    presenter?.presentDeatails(response: response)
  }
    
    func feedAPI(request:Page2Model.GetAPIImage.Request){
        APIManagerImage.shared.getImageAPI(id: request.id) { [weak self] result in
            switch result {
            case .success(let imgPhone):
                self?.imagePhone = imgPhone
                let response = Page2Model.GetAPIImage.Response(success: true, json: imgPhone)
                self?.presenter?.presentImage(response: response)
            case .failure(let error):
                let response = Page2Model.GetAPIImage.Response(success: false, json: error as! Array<ImagePhone>)
                self?.presenter?.presentImage(response: response)
            }
        }
    }
}
