//
//  Page2DetailsRouter.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Page2DetailsRouterInterface{}

class Page2DetailsRouter: Page2DetailsRouterInterface
{
  weak var viewController: Page2DetailsViewController?
  
    func passDataToNextScene(segue: UIStoryboardSegue) {
    }
}
