//
//  Page2DetailsWorker.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

protocol Page2WokerAPIManager {
    func getImageAPI(id:Int, completion: @escaping (Swift.Result<[ImagePhone], Error>) -> Void)
}

class Page2WokerAPI : Page2WokerAPIManager {
    func getImageAPI(id:Int, completion: @escaping (Result<[ImagePhone], Error>) -> Void) {
        let baseURL = "https://scb-test-mobile.herokuapp.com/api/mobiles/\(id)/images/"
        AF.request(baseURL)
            .validate()
            .responseJSON { response in
                switch response.result {
                case .success:
                    do {
                        let imgPhone = try JSONDecoder().decode([ImagePhone].self, from: response.data!)
                        completion(.success(imgPhone))
                    } catch (let error) {
                        completion(.failure(error))
                    }
                case .failure(let error):
                    completion(.failure(error))
                }
        }
    }
}
