//
//  Page2DetailsInteractor.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Page2DetailsInteractorInterface
{
  func showDetails(request: Page2Model.showDetails.Request)
    var phone: DisplayedPhone? {get set}
    var mobileID:Int? {get set}
    var price:Double? {get set}
    var rating:Double? {get set}
    var description:String? {get set}
}

class Page2DetailsInteractor: Page2DetailsInteractorInterface
{
    var description: String?
    var price: Double?
    var rating: Double?
    var phone: DisplayedPhone?
    var mobileID: Int?
    
    
  var presenter: Page2DetailsPresenterInterface?
  var worker: Page2DetailsWorker?
  
  // MARK: Do something
  
  func showDetails(request: Page2Model.showDetails.Request)
  {
    let phoneDetails : DisplayedPhone = self.phone!
    let mobileID = self.mobileID!
//    let description = self.description!
//    let price = self.price!
//    let rating = self.rating!
    
    let response = Page2Model.showDetails.Response(mobileID: mobileID, json: [phoneDetails])
    presenter?.presentDeatails(response: response)
  }
}
