//
//  Page2DetailsViewController.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Page2DetailsViewControllerInterface: class
{
    func displayPhone(viewModel: Page2Model.showDetails.ViewModel)
}

class Page2DetailsViewController: UIViewController, Page2DetailsViewControllerInterface
{
    var interactor: Page2DetailsInteractorInterface!
    var router: Page2DetailsRouter!
    
    @IBOutlet weak var mCollectionView:UICollectionView!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var rateLabel: UILabel!
    @IBOutlet weak var priceLabel: UILabel!

  // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        setup(viewController: self)
    }
  
  // MARK: Setup
  
    private func setup(viewController: Page2DetailsViewController)
  {
    let router = Page2DetailsRouter()
    router.viewController = viewController
    
    let presenter = Page2DetailsPresenter()
    presenter.viewController = viewController
    
    let interactor = Page2DetailsInteractor()
    interactor.presenter = presenter
    
    viewController.interactor = interactor
    viewController.router = router
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    router.passDataToNextScene(segue: segue)
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    interactor.showDetails(request: Page2Model.showDetails.Request())
  }
  
  // MARK: Do something
  
  func displayPhone(viewModel: Page2Model.showDetails.ViewModel)
  {
    let phone = viewModel.json
    
    print("phone: \(phone)")
//    descriptionLabel.text = viewModel.
//    priceLabel.text = "Price: $\(viewModel.price)"
//    rateLabel.text = "Rating: \(viewModel.rating)"
  }
}
