//
//  Page2DetailsPresenter.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol Page2DetailsPresenterInterface
{
  func presentDeatails(response: Page2Model.showDetails.Response)
}

class Page2DetailsPresenter: Page2DetailsPresenterInterface
{
  weak var viewController: Page2DetailsViewControllerInterface?
  
  // MARK: Do something
  
  func presentDeatails(response: Page2Model.showDetails.Response)
  {
//    let displayed: [Page2Model.DisplayedPhone] = response.json.map() { phone in
//        Page2Model.DisplayedPhone(rating: phone.rating, thumbImageURL: phone.thumbImageURL, price: phone.price, name: phone.name, description: phone.description)
//    }
    let viewModel =  Page2Model.showDetails.ViewModel(mobileID: response.mobileID, json: response.json)
    print("viewmodel : \(viewModel)")
    viewController?.displayPhone(viewModel: viewModel)
  }
}

