//
//  Page2DetailsModels.swift
//  BuyerClean
//
//  Created by Peanuz on 30/8/2562 BE.
//  Copyright (c) 2562 SCB. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Page2Model
{
  struct showDetails{
    struct Request
    {
    }
    struct Response
    {
        var mobileID: Int
//        var price:Double
//        var rating:Double
//        var description:String
        var json: Array<DisplayedPhone>
    }
    struct ViewModel
    {
        var mobileID: Int
//        var price:Double
//        var rating:Double
//        var description:String
        var json: Array<DisplayedPhone>
    }
  }
}
